### PR TITLE
Refactoring and Enhancement (Ongoing)

### PR DESCRIPTION
**Pull request by adroslice**

### CODE REVIEW

**Comment by emiwidknowit** [comment]
Looks very promising so far!
Please keep the `is { }` and `is null` as they are a part of the code convention used throughout the code.

**Comment by versaceLORD** [comment]
Looks very promising so far!
Please keep the `is { }` and `is null` as they are a part of the code convention used throughout the code.

**Comment by adroslice** [comment]
Is there a document describing this convention I can reference? Otherwise I personally recommend changing this convention, as it does not offer any real readability, structural or performance advantages.

**Comment by versaceLORD** [comment]
> 
> 
> Is there a document describing this convention I can reference? Otherwise I personally recommend changing this convention, as it does not offer any real readability, structural or performance advantages.

Unfortunately there's no convention yet. I did not expect anyone to contribute to the code; so there's still some collaboration preparation to be done to say the least. But for now I think it is easiest to keep the `is` syntax as I am not personally interested in changing it as of now. _(I got the habit of using `is` from my workplace, so it makes the most sense for me right now!)_

Code base is still not mature so of course this is subject to change - most of the code is. So I appreciate any structural & code style based feedback!

**Comment by adroslice** [comment]
Here are the biggest changes I would only work on if they were confirmed wanted...
1. Replace the ConsoleHelper with a basic Logging class, with different LogLevels (Typesafe Enum Pattern, probably)
2. Rework the entire commands system into something more dynamic, with things like an automated 'help' command and metadata-based argument parsing and related error messages, likely using some light reflection.
3. Rework the way processes are selected. Honestly the only real thing needed here is at least a way to use a PID, or the ability to select a specific process out of several of the same name.

Regarding 1., I'd be interested in some feedback regarding b65b90f (see 3f5e6e1 for the actual commit message, I kind of messed up there, might rewrite history a little later). Its a solution that only works on windows, so I figured it would be fine for a windows-only autoclicker, but this behavior is honestly not needed that badly anyway.

**Comment by versaceLORD** [comment]
> 
> 
> Here are the biggest changes I would only work on if they were confirmed wanted...
> 
>     1. Replace the ConsoleHelper with a basic Logging class, with different LogLevels (Typesafe Enum Pattern, probably)
> 
>     2. Rework the entire commands system into something more dynamic, with things like an automated 'help' command and metadata-based argument parsing and related error messages, likely using some light reflection.
> 
>     3. Rework the way processes are selected. Honestly the only real thing needed here is at least a way to use a PID, or the ability to select a specific process out of several of the same name.
> 
> 
> Regarding 1., I'd be interested in some feedback regarding [b65b90f](https://github.com/versaceLORD/virtual-auto-clicker/commit/b65b90f91be1666cc3a1eb3d9b9817388bd14bc1) (see [3f5e6e1](https://github.com/versaceLORD/virtual-auto-clicker/commit/3f5e6e1eac0c397da4b22e0322f39691c7626a9d) for the actual commit message, I kind of messed up there, might rewrite history a little later). Its a solution that only works on windows, so I figured it would be fine for a windows-only autoclicker, but this behavior is honestly not needed that badly anyway.
1) ConsoleHelper is a really bad excuse for not spending the time to not use a proper logging library like Serilog or log4net or whatever. If time was spent to actually make logging good I would love to see a library being implemented in a way that makes sense for such a little application as this is.

2) This would be great, the command system right now is very lightweight and simple, but if it could be made a lot better and you wish to put in the work, sure, I'd love to review it!

3) It's a double edged sword. Because I want to achieve a lot with this one.
Two of the biggest/the biggest goals:

- Be able to let any non-advanced windows user be able to use this application within both standalone and browser usage.
- Let advanced users be able to configure and use the application in a way where they are able to meet pretty specific needs. (This is where the need for multiple clickers and clicker names grew).

Currently I think it does a great job of making it simple for standalone applications, but it's a hassle to pick for example browser window processes. I haven't put in a lot of time on this yet, but I want another way to fetch processes that is intuitive enough for a non-advanced windows user to make it work. If you have any suggestions here feel free to send them to me or make a draft in another PR.

**Review by versaceLORD — APPROVED** [review]
Good start of a proper refactoring, still some notes on my end, but as this is a merge to project-refactoring and not to main I will merge it.

**Pull request merged**
